### PR TITLE
Fix canonical distribution names

### PR DESCRIPTION
**Pull request by marco-pag**
Fix the canonical distribution names section in the docs and update the canonicalize command.

### CODE REVIEW

**Comment by dhellmann** [comment]
I forget why it was important to replace `-` with `_`, so let me dig a bit to find it before we merge this change.

**Comment by dhellmann** [comment]
I think it had to do with the fact that the sdist filename took the value from the packaging settings without modifying it at all, so it could come out different at different times, and be different from the wheel itself which _does_ force canonicalization. That means it's impossible to ensure we get the same name all the time unless we make the extra transformation. Since fromager relies so much on looking up settings and plugins by using the package name, we need some way to force it into a  consistent format.

**Comment by tiran** [comment]
https://packaging.python.org/en/latest/specifications/name-normalization/ defines the normalization rules. 

> The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character. This can be implemented in Python with the re module:

**Comment by dhellmann** [comment]
> https://packaging.python.org/en/latest/specifications/name-normalization/ defines the normalization rules.
> 
> > The name should be lowercased with all runs of the characters ., -, or _ replaced with a single - character.

OK. That's not what I was seeing, I think. I'll revisit this and see if we can use `-` instead of `_`.

**Comment by tiran** [comment]
PyPI isn't consistent. There is standard on one hand. And there is legacy support on the other hand.

PyPI are a ton of legacy packages that have a `.` in the package name and sdist name. For example most of the Zope 3 packages like https://pypi.org/project/zope.interface use legacy names. https://pypi.org/project/zope-interface (dash) redirects to  https://pypi.org/project/zope.interface (dot).

**Comment by dhellmann** [comment]
> PyPI isn't consistent. There is standard on one hand. And there is legacy support on the other hand.
> 
> For example PyPI are a ton of legacy packages that have a `.` in the package name and sdist name. For example most of the Zope 3 packages like https://pypi.org/project/zope.interface use legacy names. https://pypi.org/project/zope-interface (dash) redirects to https://pypi.org/project/zope.interface (dot).

Right. I had to pick something. It looks like I picked the wrong thing. I probably picked that based on a bad example, but I don't remember any more.

In any case, any change would be backwards-incompatible, so I want to take good care to understand how much will break in the downstream builds before we make it.

**Comment by dhellmann** [comment]
> > PyPI isn't consistent. There is standard on one hand. And there is legacy support on the other hand.
> > For example PyPI are a ton of legacy packages that have a `.` in the package name and sdist name. For example most of the Zope 3 packages like https://pypi.org/project/zope.interface use legacy names. https://pypi.org/project/zope-interface (dash) redirects to https://pypi.org/project/zope.interface (dot).
> 
> Right. I had to pick something. It looks like I picked the wrong thing. I probably picked that based on a bad example, but I don't remember any more.
> 
> In any case, any change would be backwards-incompatible, so I want to take good care to understand how much will break in the downstream builds before we make it.

A conversation earlier today made me realize that the reason for replacing `-` with `_` has to do with needing to be able to use those names for python package names for the override plugin entry point registration, and wanting to use the same naming everywhere so users don't have to know when to use different types of canonicalization.

**Comment by dhellmann** [comment]
I don't think we will want this, unfortunately. It's going to be hard to make it backwards compatible.

**Pull request closed without merging**
