### PR TITLE
Switch from toml to tomlkit

### PR DESCRIPTION
**Pull request by tiran**
tomlkit preserves comments and document layout.

### CODE REVIEW

**Review by dhellmann — APPROVED** [review]
This looks good. I think mergify won't merge it because it's in draft, but I'll approve it anyway.

**Comment by dhellmann** [comment]
Oops, well, we apparently aren't protecting against draft status.

**Comment by dhellmann** [comment]
oh, never mind, I see now that you removed the draft flag

**Comment by tiran** [comment]
Yeah, I removed the draft status.

**Pull request merged**
