### PR TITLE
Restoring mergify_linter in CI

### PR DESCRIPTION
**Pull request by rd4398**
This PR is for the issue: https://github.com/python-wheel-build/fromager/issues/172

I am new to writing workflows, CI and GitHub actions so not sure whether what I have done in this PR is correct. Please let me know if any changes are required

### CODE REVIEW

**Comment by shubhbapna** [comment]
Looks like the `yaml` module is not installed: https://github.com/python-wheel-build/fromager/actions/runs/9996065530/job/27629569454?pr=198#step:5:15.

You will have to install it in the install dependency step. I also don't think you need tox unless you are adding a new target to run the mergify linter

**Comment by rd4398** [comment]
Oh okay! Let me add that step

**Comment by rd4398** [comment]
Okay, I am a bit confused...
tox.ini already has this (https://github.com/python-wheel-build/fromager/pull/62/files ) included in main branch.
Is there any other way to restore or am I missing something?

**Comment by dhellmann** [comment]
It looks like maybe a merge conflict was resolved poorly.

I see the linter invoked here, in the `pkglint` section of tox.ini https://github.com/python-wheel-build/fromager/blob/main/tox.ini#L67

I expected that to show up in the `linter` section.

**Comment by rd4398** [comment]
okay, I will move it there

**Review by dhellmann — APPROVED** [review]

**Pull request merged**
