### PR TITLE
be more explicit about the types of dists to download

### PR DESCRIPTION
**Pull request by dhellmann**
In a few places where we change the default inputs to resolve_dist()
pass both options for clarity about what sorts of distributions are
expected as results.

Related to #88
Related to #87

### CODE REVIEW

**Review by Gregory-Pereira — APPROVED** [review]
/lgtm

**Comment by dhellmann** [comment]
@mergifyio refresh

**Comment by dhellmann** [comment]
https://github.com/Mergifyio refresh

**Review by Gregory-Pereira — APPROVED** [review]
re-approval

**Pull request merged**
