### PR TITLE
enforce ruff formatting for code

### LINKED ISSUE #94: consider a formatting tool for consistency
look at black and ruff

### PR DESCRIPTION
**Pull request by dhellmann**
This PR reformats everything using ruff's default settings, updates the linter in tox.ini to invoke ruff, and adds a new tox environment `ruff` to run ruff over the code to reformat it.

@tiran @markmc @Gregory-Pereira I've worked out how to make emacs automatically run ruff when I save, so I'm OK with making a change like this. Before we merge it, I'd like to make sure everyone is on board, though.

Fixes #94

### CODE REVIEW

**Review by tiran — CHANGES_REQUESTED** [review]
I'm strong +1 to add auto-formatting.

Some small suggestions:
- allow passing of arguments to `ruff`, so `tox -e linters -- --fix` works.
- rename `ruff` target to `format`
- add this to `pyproject.toml` to make `ruff` behave like black, to enable more checkers, and allow auto-fixers:

```
[tool.ruff]
target-version = "py310"
# same as black's default line length
line-length = 88

[tool.ruff.lint]
# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

select = [
  "B",  # flake8-bugbear
  "E",  # pycodestyle
  "F",  # Pyflakes
  "Q", # flake8-quotes
  "I",  # isort
  "N", # pep8-naming
  "W", # pycodestyle
  "RUF", # ruff-specific rules
  "UP",  # pyupgrade
  # "SIM",  # flake8-simplify
  "TID", # flake8-tidy-imports
]
```

**Comment by Gregory-Pereira** [comment]
Conceptually totally onboard with this change if it works for you. I don't have experience with ruff formatter for python so I will defer to you two experts.

**Comment by tiran** [comment]
I have created PR #100, which uses a slightly different configuration and additional fixers.

**Comment by dhellmann** [comment]
I've approved #100, let's use that version instead of updating mine.

**Pull request closed without merging**
