### PR TITLE
Change post and local version of a wheel file

### PR DESCRIPTION
**Pull request by tiran**
A new function `change_wheel_version()` changes the post and local elements of the version of a wheel file. The function creates a new file with new file name, new `dist-info` directory, and updated `METADATA` file.

See: #68

### CODE REVIEW

**Comment by dhellmann** [comment]
This changes the wheel after it's built. As part of producing our product builds, we need to also deliver the source that went into the build. The toolchain for doing that looks at the versions and grabs both the source and the wheel. So, I think we have to be able to update the source distribution version info, too. To do that, do we have to do more than rename the file to use the same version?

**Comment by tiran** [comment]
A [modern source distribution](https://packaging.python.org/en/latest/specifications/source-distribution-format/) has the version in:

- the file name (`name-version.tar.gz`)
- the first level directory (`name-version`)
- the `PKG-INFO` file

At a bare minimum we have to update these three places to create a new sdist post version. There is also a legacy sdist format (generated by distutil's sdist). I don't know if any of our packages use the legacy format.

However there is more work to do if we want our `shrubbery-42.0.post1.tar.gz` to generate a `shrubbery-42.0.post1-py3-none-any.whl` without an additional step. The output version is defined by the build system and build backend. AFAIK the build backend does not necessarily use the version information from the sdist metadata. Instead the version number can be all over the place:

- hard coded in pyproject.toml
- hard coded in setup.cfg
- hard coded in setup.py
- dynamic provider in pyproject.toml (e.g. setuptools-scm, read from a Python attribute)
- dynamic attribute in setup.cfg, e.g. `version = attr: package.__version__`
- custom code in setup.py that gets the version from another place like importing or exec-ing code.
- other shenanigans

**Comment by tiran** [comment]
I suggest that we do not attempt to fix the sdist -> whl version problem for now. That's going to be too much hand holding for packages.

- we create `shrubbery-42.0.post1.tar.gz` from original `shrubbery-42.0.tar.gz` + patches. We only change name, directory name, and `PKG-INFO` to contain `42.0.post1` version.
- upload  `shrubbery-42.0.post1.tar.gz`
- build system fetches the new  `shrubbery-42.0.post1.tar.gz` sdist and builds it. This will result in  `shrubbery-42.0-py3-none-any.whl` without `post1` in the version, because we didn't fix the version in the build system.
- build system uses the new code from this PR to correct the version of the wheel to  `shrubbery-42.0.post1-py3-none-any.whl`

For GPU and vendor-specific packages like PyTorch, we also include the GPU arch and version in the file name, e.g. `torch-2.3.1+cuda125-cp311-cp311-linux_x86_64.whl`. We could either teach our system to map wheels with local versions (`+cuda125`) to sdist without local version. Or we could upload the same sources under two different names, e.g. `torch-2.3.1+cuda125.tar.gz` and `torch-2.3.1+rocm60.tar.gz` with same content, except for root directory name and `PKG-INFO`.

**Comment by dhellmann** [comment]
I like the idea of doing the minimal work to update the sdist and wheel separately. We can improve on that later, if needed.

I'm not sure we need the variant tags in the versions. Within the build system everything about the variants is segregated into separate indexes and images already, so we may not need to add the info to the versions, too. When we figure out how to track the post version number, maybe it will become clear how to include that info and if it's straightforward and doesn't interfered with package selection then we can do it.

Right now, I'm assuming we need to potentially support a different post version for each package we build. Potentially for each variant, too. We could track that in the overrides/settings.yaml or some other file, but it feels like it could become unwieldy so I'm not sure that's what we want.

**Comment by dhellmann** [comment]
I think #325 makes this obsolete?

**Comment by tiran** [comment]
I agree.

And if we ever need the feature, then it should be implemented as part of wheel unpack and pack process.

**Pull request closed without merging**
