### PR TITLE
add command to produce rpm list from build-order

### PR DESCRIPTION
**Pull request by dhellmann**
Add `build-order rpms` to list the RPMs that look
like they are probably related to the dists in a
build-order file.

### CODE REVIEW

**Comment by tiran** [comment]
`dnf repoquery` uses the current list of enabled repos. We have several disabled repos that only get enabled for some steps, e.g. `EPEL`.

**Comment by dhellmann** [comment]
> `dnf repoquery` uses the current list of enabled repos. We have several disabled repos that only get enabled for some steps, e.g. `EPEL`.

Is there a way to query those without enabling them?

**Comment by tiran** [comment]
Do you want to query the available packages or the installed packages? There is always `rpm -qa`.

**Comment by dhellmann** [comment]
> Do you want to query the available packages or the installed packages? There is always `rpm -qa`.

I'm interested in the installed and available packages. I think repoquery is showing both.

**Comment by dhellmann** [comment]
I thought I'd written this code before, and I found it in the downstream tool where I put it, so we don't need this.

**Pull request closed without merging**
